-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "role" TEXT NOT NULL,
    "mother_for" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "display_name" TEXT NOT NULL,
    "first_name" TEXT,
    "dob" DATETIME NOT NULL,
    "gender" TEXT,
    "city" TEXT,
    "country" TEXT,
    "nationality" TEXT,
    "ethnicity" TEXT,
    "height_cm" INTEGER,
    "education" TEXT,
    "profession" TEXT,
    "income_range" TEXT,
    "languages" TEXT,
    "marital_status" TEXT,
    "relocate" BOOLEAN DEFAULT false,
    "want_children" TEXT,
    "children_preference" TEXT,
    "religiousness" INTEGER,
    "prayer_freq" TEXT,
    "sect" TEXT,
    "marriage_timeline" TEXT,
    "quran_engagement" TEXT,
    "fasting_ramadan" TEXT,
    "hijab_preference" TEXT,
    "beard" TEXT,
    "hijab" TEXT,
    "halal_diet" TEXT,
    "smoker" TEXT,
    "fitness_level" TEXT,
    "dietary_preferences" TEXT,
    "spouse_practice" TEXT,
    "interests" TEXT,
    "personality_traits" TEXT,
    "icebreaker_questions" TEXT,
    "bio" TEXT,
    "muslim_affirmed" BOOLEAN NOT NULL DEFAULT false,
    "phone_verified" BOOLEAN NOT NULL DEFAULT false,
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "selfie_verified" BOOLEAN NOT NULL DEFAULT false,
    "selfie_url" TEXT,
    "terms_accepted" BOOLEAN NOT NULL DEFAULT false,
    "terms_accepted_at" DATETIME,
    "onboarding_completed" BOOLEAN NOT NULL DEFAULT false,
    "onboarding_step" INTEGER DEFAULT 0,
    "location" TEXT,
    "discovery_radius_km" INTEGER,
    "privacy_blur_mode" BOOLEAN NOT NULL DEFAULT false,
    "privacy_reveal_on_match" BOOLEAN NOT NULL DEFAULT true,
    "photos_blurred" BOOLEAN NOT NULL DEFAULT false,
    "discoverable" BOOLEAN NOT NULL DEFAULT true,
    "expo_push_token" TEXT,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    "last_active_at" DATETIME,
    "ward_display_name" TEXT,
    "ward_dob" DATETIME,
    "ward_city" TEXT,
    "ward_country" TEXT,
    "ward_education" TEXT,
    "ward_profession" TEXT,
    "ward_bio" TEXT
);
INSERT INTO "new_User" ("beard", "bio", "children_preference", "city", "country", "created_at", "dietary_preferences", "discovery_radius_km", "display_name", "dob", "education", "email", "email_verified", "ethnicity", "expo_push_token", "fasting_ramadan", "first_name", "fitness_level", "gender", "halal_diet", "height_cm", "hijab", "hijab_preference", "icebreaker_questions", "id", "income_range", "interests", "languages", "last_active_at", "location", "marital_status", "marriage_timeline", "mother_for", "muslim_affirmed", "nationality", "onboarding_completed", "onboarding_step", "personality_traits", "phone", "phone_verified", "photos_blurred", "prayer_freq", "privacy_blur_mode", "privacy_reveal_on_match", "profession", "quran_engagement", "religiousness", "relocate", "role", "sect", "selfie_url", "selfie_verified", "smoker", "spouse_practice", "terms_accepted", "terms_accepted_at", "updated_at", "want_children", "ward_bio", "ward_city", "ward_country", "ward_display_name", "ward_dob", "ward_education", "ward_profession") SELECT "beard", "bio", "children_preference", "city", "country", "created_at", "dietary_preferences", "discovery_radius_km", "display_name", "dob", "education", "email", "email_verified", "ethnicity", "expo_push_token", "fasting_ramadan", "first_name", "fitness_level", "gender", "halal_diet", "height_cm", "hijab", "hijab_preference", "icebreaker_questions", "id", "income_range", "interests", "languages", "last_active_at", "location", "marital_status", "marriage_timeline", "mother_for", "muslim_affirmed", "nationality", "onboarding_completed", "onboarding_step", "personality_traits", "phone", "phone_verified", "photos_blurred", "prayer_freq", "privacy_blur_mode", "privacy_reveal_on_match", "profession", "quran_engagement", "religiousness", "relocate", "role", "sect", "selfie_url", "selfie_verified", "smoker", "spouse_practice", "terms_accepted", "terms_accepted_at", "updated_at", "want_children", "ward_bio", "ward_city", "ward_country", "ward_display_name", "ward_dob", "ward_education", "ward_profession" FROM "User";
DROP TABLE "User";
ALTER TABLE "new_User" RENAME TO "User";
CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
